### ISSUE TITLE
Addon terminates right away (Mi Composition Scale 2)

### ISSUE THREAD

**Issue by CodeFinder2** [lolouk44/hassio-addons#63]
**Describe the bug**
Add-on starts but terminates immediately. Does not seem to detect my scale (not sure if it does, see log below). Also tried with `BLUEPY_PASSIVE_SCAN` set to `true` without success. I've set the `MISCALE_VERSION` to `2`.

This is my config:
```yaml
HCI_DEV: hci0
BLUEPY_PASSIVE_SCAN: false
MISCALE_MAC: "!secret xiaomi_mi_scale_mac"
MISCALE_VERSION: 2
MQTT_PREFIX: miscale
MQTT_HOST: localhost
MQTT_USERNAME: "!secret default_username"
MQTT_PASSWORD: "!secret default_password"
MQTT_PORT: 1883
MQTT_RETAIN: true
MQTT_DISCOVERY: true
MQTT_DISCOVERY_PREFIX: homeassistant
MQTT_TLS_CACERTS: Path to CA Cert File
MQTT_TLS_INSECURE: false
TIME_INTERVAL: 30
USERS:
  - NAME: ...
    SEX: ...
    GT: ...
    LT: ...
    HEIGHT: ...
    DOB: "..."
```

**To Reproduce**
Reproducible by (re-)starting the addon. Unfortunately, there are no errors and there seems to be no logging scheme that prints more (no "verbose" option). If I refresh the addon page in HA, it says "Start" again (indicating that it has terminated).

**Expected behaviour**
I expect that it remains started and "searches" for the scale.

**Scale:**
 - Name: Mi Body Composition Scale 2
 - Model: XMTZC05HM

**Device running Home Assistant:**
 - Raspberry Pi 4B
 - USB Dongle for Bluetooth (with a dedicated cable)

**Additional context**
Here's the log:
```
-------------------------------------
2022-10-02 19:20:37 - Starting Xiaomi mi Scale...
2022-10-02 19:20:37 - Loading Config From Add-On Options...
2022-10-02 19:20:37 - Config Loaded...
-------------------------------------
2022-10-02 19:20:37 - Initialization Completed, Waiting for Scale...
```

Please let me know if you need more information or if there's something where I can help you with. :-)

Edit: My bluetooth device seems to be detected fine:
```bash
$ hcitool dev
Devices:
	hci0	XX:XX:XX:XX:XX:XX
```

**Comment by jaco** [comment]
Same problem here (after update)

**Comment by jgalerap** [comment]
Same problem here. I’m using MISCALE_VERSION: 1

**Comment by MariusHerget** [comment]
Same problem here:

Configuration (redacted => ***** or <MISCALE_MAC>):
```
HCI_DEV: hci0
BLUEPY_PASSIVE_SCAN: true
MISCALE_MAC: <MISCALE_MAC>
MISCALE_VERSION: 2
MQTT_PREFIX: miscale
MQTT_HOST: 192.168.1.2
MQTT_USERNAME: *****
MQTT_PASSWORD: "*****"
MQTT_PORT: 1883
MQTT_RETAIN: true
MQTT_DISCOVERY: true
MQTT_DISCOVERY_PREFIX: homeassistant
MQTT_TLS_CACERTS: Path to CA Cert File
MQTT_TLS_INSECURE: false
TIME_INTERVAL: 5
USERS:
  - NAME: *****
    SEX: *****
    GT: *****
    LT: *****
    HEIGHT: *****
    DOB: "*****"
```

Scale:

- Name: Mi Body Composition Scale 2
- Model: XMTZC04HM

Device running Home Assistant:

- Linux Server with Hassio Docker
- USB Bluetooth Adapter Dongle


AddOn Log:
```
-------------------------------------
2022-10-03 10:51:51 - Starting Xiaomi mi Scale...
2022-10-03 10:51:51 - Loading Config From Add-On Options...
2022-10-03 10:51:51 - Config Loaded...
-------------------------------------
2022-10-03 10:51:51 - Initialization Completed, Waiting for Scale...
```

Hassio Log:
```
2022-10-03 10:51:00.302 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/79ff755f_xiaomi_mi_scale/stats - Can't read stats from addon_79ff755f_xiaomi_mi_scale: Expecting value: line 1 column 1 (char 0)
```
or:

```
2022-10-03 11:03:21.792 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/79ff755f_xiaomi_mi_scale/stats - Container addon_79ff755f_xiaomi_mi_scale is not running
```

HCI:
```
10:56:52 › hcitool dev
Devices:
        hci0    <HCI0_MAC>
```

HCI lescan:
```
11:02:41 › sudo hcitool lescan | grep "<MISCALE_MAC>"
<MISCALE_MAC> (unknown)
<MISCALE_MAC> MI SCALE2
<MISCALE_MAC> (unknown)
<MISCALE_MAC> MI SCALE2
```

Maybe related problems: 
- I have a new Bluetooth adapter: Rolio Bluetooth 5.1 Adapter
- The `hcitool lescan` sometimes does not work with the new adapter, workaround: hci0 down, hci0 up, restart bluetooth service

**Comment by echopage** [comment]
Same problem here. I’m using MISCALE_VERSION: 2

**Comment by lolouk44** [comment]
There are issues with the add-on specifically unfortunately (working fine on the stand-alone container).
Investigating...

**Comment by MariusHerget** [comment]
> There are issues with the add-on specifically unfortunately (working fine on the stand-alone container). Investigating...

If you need any help to investigate or debug, please do not hesitate to reach out!

**Comment by jgalerap** [comment]
Can't install lolouk44/xiaomi-mi-scale-ha-add-on:0.3.2: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.3.2&fromImage=lolouk44%2Fxiaomi-mi-scale-ha-add-on&platform=linux%2Farm64: Not Found ("manifest for lolouk44/xiaomi-mi-scale-ha-add-on:0.3.2 not found: manifest unknown: manifest unknown")

**Comment by lolouk44** [comment]
> Can't install lolouk44/xiaomi-mi-scale-ha-add-on:0.3.2

it's being built (see [here](https://github.com/lolouk44/hassio-addons/actions/runs/3173841878)), give it 10-15 min

**Comment by lolouk44** [comment]
[0.3.2](https://github.com/lolouk44/hassio-addons/releases/tag/0.3.2) is now ready.
Please let me know if you have issues.
The only thing I could not implement following the move away from bluepy to bleak was passive scanning. I'm hoping it's not an issue since bleak is way more stable.

**Comment by MariusHerget** [comment]
> 2022-10-03 14:01:51 - Initialization Completed, Waiting for Scale... ERROR:root:A message handler raised an exception: '0000181b-0000-1000-8000-00805f9b34fb'.

I'm getting the exact same error.

**Comment by lolouk44** [comment]
@jgalerap @MariusHerget do you both have a V1 scale?

**Comment by jgalerap** [comment]
> @jgalerap @MariusHerget do you both have a V1 scale?

I have a v1, YES

**Comment by lolouk44** [comment]
Do me a favour, create a new issue asking for V1 support.
Bleak works differently than bluepy used to and not sure what data is actually sent and under what service on a V1 scale, so I'll need your help toubleshooting this....

**Comment by lolouk44** [comment]
@MariusHerget are you running the script on a RPi? If so are you ableto try and use the built-in bluetooth?

**Comment by MariusHerget** [comment]
> @MariusHerget are you running the script on a RPi? If so are you ableto try and use the built-in bluetooth?

I am running on a hassio docker on a 22.04 ubuntu server on an old thinkpad. My built-in bluetooth is not reliable anymore but I can reactivate it to check if this helps.

**Comment by lolouk44** [comment]
@CodeFinder2 The issue was the missing dbus sharing from HA to the add-on (required for bleak to work)
MQTT is only connected to when sending a new measure, it's not connected otherwise. So you should see a log entry before and after trying to connect to the MQTT Broken when weight is received. Can you try and get the batteries out and back in to reset the scale, then steo on the scale to see if you get anything?

**Comment by lolouk44** [comment]
> I am running on a hassio docker on a 22.04 ubuntu server on an old thinkpad. My built-in bluetooth is not reliable anymore but I can reactivate it to check if this helps.

Make sure your container has the dbus shared else it won't work. Typically with this in a docker-compose file:
```
    volumes:
      - /var/run/dbus/:/var/run/dbus/:ro
```

**Comment by lolouk44** [comment]
> I am using the supervised installation, so messing around with docker-compose files shouldn't be necessary for me, correct?

what's your setup? if you're running a supervisor installation from a docker container (e.g. not running HA OS on a SD in a RPi), you will need to mount the dbus volume on your  main container so it's accessible in HA, the supervisor will then share it automatically with the add-on

**Comment by jgalerap** [comment]
> volumes:
>       - /var/run/dbus/:/var/run/dbus/:ro



> > I am running on a hassio docker on a 22.04 ubuntu server on an old thinkpad. My built-in bluetooth is not reliable anymore but I can reactivate it to check if this helps.
> 
> Make sure your container has the dbus shared else it won't work. Typically with this in a docker-compose file:
> 
> ```
>     volumes:
>       - /var/run/dbus/:/var/run/dbus/:ro
> ```
> 
> @jgalerap what's your setup? This may be useful for you too,

I'm using HA SO running in a Raspberry PI4 on a SD Card.

**Comment by MariusHerget** [comment]
I'm running it like the official guides suggests: https://www.home-assistant.io/installation/linux

Hence never had a docker-compose file or added the dbus to the volumes. Never had a problem so far. I will look into it!

**Comment by CodeFinder2** [comment]
> > I am using the supervised installation, so messing around with docker-compose files shouldn't be necessary for me, correct?
> 
> what's your setup? if you're running a supervisor installation from a docker container (e.g. not running HA OS on a SD in a RPi), you will need to mount the dbus volume on your main container so it's accessible in HA, the supervisor will then share it automatically with the add-on

I am running Debian 10 on a Raspberry Pi 4B from an SSD and installed "Home Assistant Supervised" according to this repo: https://github.com/home-assistant/supervised-installer

So no HA OS. Let me know if you need more information. I was also never writing/configuring any docker files so far.

Thanks for your support again! :-)

**Comment by lolouk44** [comment]
> I'm running it like the official guides suggests: https://www.home-assistant.io/installation/linux
> 
> Hence never had a docker-compose file or added the dbus to the volumes. Never had a problem so far. I will look into it!

You don't need docker-compose, but youl'll need to add a parameter to your docker run command:
`-v /var/run/dbus/:/var/run/dbus/:ro`

**Comment by lolouk44** [comment]
> > volumes:
> > - /var/run/dbus/:/var/run/dbus/:ro
> 
> > > I am running on a hassio docker on a 22.04 ubuntu server on an old thinkpad. My built-in bluetooth is not reliable anymore but I can reactivate it to check if this helps.
> > 
> > 
> > Make sure your container has the dbus shared else it won't work. Typically with this in a docker-compose file:
> > ```
> >     volumes:
> >       - /var/run/dbus/:/var/run/dbus/:ro
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @jgalerap what's your setup? This may be useful for you too,
> 
> I'm using HA SO running in a Raspberry PI4 on a SD Card.

Do me a favour please and create a new issue please as I want to track V1 separately. I very much doubt your issue is dbus related since you're using HA OS on a Pi. It'll also help me ensure I don't get mixed up with the other comment already here 😉

**Comment by jgalerap** [comment]
> > > volumes:
> > > 
> > > * /var/run/dbus/:/var/run/dbus/:ro
> > 
> > 
> > > > I am running on a hassio docker on a 22.04 ubuntu server on an old thinkpad. My built-in bluetooth is not reliable anymore but I can reactivate it to check if this helps.
> > > 
> > > 
> > > Make sure your container has the dbus shared else it won't work. Typically with this in a docker-compose file:
> > > ```
> > >     volumes:
> > >       - /var/run/dbus/:/var/run/dbus/:ro
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > @jgalerap what's your setup? This may be useful for you too,
> > 
> > 
> > I'm using HA SO running in a Raspberry PI4 on a SD Card.
> 
> Do me a favour please and create a new issue please as I want to track V1 separately. I very much doubt your issue is dbus related since you're using HA OS on a Pi. It'll also help me ensure I don't get mixed up with the other comment already here 😉

Done, bug for v1 is already created, but @MariusHerget and I, both have the same stack trace, with the exact same error on different setups and we own different models, I'm on a V1 and @MariusHerget is on a v2

**Comment by lolouk44** [comment]
@CodeFinder2 
Are you sure your BT Dongle is on HCI0? On a Pi HCI0 is normally the built in bluetooth...
Just trying to make sure I'm not overseeing anything

**Comment by CodeFinder2** [comment]
> @CodeFinder2 Are you sure your BT Dongle is on HCI0? On a Pi HCI0 is normally the built in bluetooth... Just trying to make sure I'm not overseeing anything

Yeah, yeah, good question! I disabled the internal bluetooth (some for WiFi) via `dtoverlay=disable-bt` in `/boot/config.txt` because it had weak reception.

There's just one device on hci0:
```
$ hciconfig -a
hci0:	Type: Primary  Bus: UART
	BD Address: DC:XX:XX:XX:XX:XX  ACL MTU: 1021:8  SCO MTU: 64:1
	UP RUNNING 
	RX bytes:12961555 acl:0 sco:0 events:1066544 errors:0
	TX bytes:10770033 acl:0 sco:0 commands:966791 errors:0
	Features: 0xbf 0xfe 0xcf 0xfe 0xdb 0xff 0x7b 0x87
	Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3 
	Link policy: RSWITCH SNIFF 
	Link mode: SLAVE ACCEPT 
	Name: 'home'
	Class: 0x0c0000
	Service Classes: Rendering, Capturing
	Device Class: Miscellaneous, 
	HCI Version: 5.0 (0x9)  Revision: 0x156
	LMP Version: 5.0 (0x9)  Subversion: 0x6119
	Manufacturer: Cypress Semiconductor Corporation (305)
```

**Comment by lolouk44** [comment]
Thanks @MariusHerget  and @jgalerap.
I know what the issue is and you'll be glad to know it's not your fault 😄 
I'll try and fix it later tonight.

**Comment by MariusHerget** [comment]
> Thanks @MariusHerget  and @jgalerap.
> I know what the issue is and you'll be glad to know it's not your fault 😄 
> I'll try and fix it later tonight.
> 

You are a hero! Thanks :)

(And thanks for indirectly forcing me to test my backup and recovery structure. Found some flaws 😅)

**Comment by lolouk44** [comment]
@MariusHerget your issue is the same as @jgalerap, You actually have a V1 scale. I've just pushed an update ([0.3.3](https://github.com/lolouk44/hassio-addons/releases/tag/0.3.3)) which is being built and should be ready in about 10-15 min.

**Comment by MariusHerget** [comment]
@lolouk44 please elaborate - Everywhere I look (e.g. Zepp Life App) or search the model number it says "Mi Smart Scale 2".
Is it just a dumb naming schema or am I missing something?

and btw: thanks for helping us out so quickly!

**Comment by lolouk44** [comment]
@MariusHerget Xiaomi have a weird way of naming their scales.
They have ( to my knowledge) released 4 scales, 2 x V1, 2 x V2.
What's generally considered a V2 scale is the Body Composition Scale (the one that reads impedance via metal pads). You have the 2nd model of the V1 range.

**Comment by CodeFinder2** [comment]
v0.3.3 is working fine for me, thank you SO MUCH! :-)

Closing this now. :-)

**Comment by mesut3000** [comment]
Hi

I still have this issue.

Tried both HC0 and HC1 (I have raspberry pi and one external dongle) 

My Log :

Xiaomi Mi Scale
 
-------------------------------------
2022-10-09 08:13:44 - Starting Xiaomi mi Scale...
2022-10-09 08:13:44 - Loading Config From Add-On Options...
2022-10-09 08:13:44 - Config Loaded...
2022-10-09 08:13:44 - MQTT Discovery Setup Completed...
-------------------------------------
2022-10-09 08:13:44 - Initialization Completed, Waiting for Scale...
